### ISSUE TITLE
Compiling error at HTTPS Stm32 example

### ISSUE THREAD

**Issue by petit-miner** [balau/nucleo_tests#1]
Hi there,
I have a problem compiling the HTTPS Stm32 example.
I used the GNU ARM Embedded toolchain from here: https://launchpad.net/gcc-arm-embedded/+download
Compiling libopencm3 works without a problem, but compiling mbedTLS doesnt work with your Makefile
I changed some paths in the Makefile(/nucleo_tests/tests/mbedtls/Makefile), 
the Paths to CPPFLAGS and LDFLAGS are wrong. (I think so)
The changed Makefile: /nucleo_tests/tests/mbedtls/Makefile/

BINARY = mbedtls_test
OBJS += $(ROOT_DIR)/src/w5100_socket.o
OBJS += $(ROOT_DIR)/src/w5100_spi.o
OBJS += $(ROOT_DIR)/src/inet.o
OBJS += $(ROOT_DIR)/src/stdio_usart.o
OBJS += $(ROOT_DIR)/src/syscalls.o
OBJS += $(ROOT_DIR)/src/file.o
OBJS += $(ROOT_DIR)/src/timespec.o
OBJS += $(ROOT_DIR)/src/clock_gettime_systick.o
OBJS += $(ROOT_DIR)/src/gettimeofday.o
OBJS += $(ROOT_DIR)/src/getaddrinfo.o
OBJS += $(ROOT_DIR)/src/select.o
OBJS += $(ROOT_DIR)/src/poll.o
OBJS += digicert_der.o
LDLIBS_SYS =

MBEDTLS_DIR = $(ROOT_DIR)/mbedtls-2.2.0
CPPFLAGS += -I$(MBEDTLS_DIR)/include
LDFLAGS += -L$(MBEDTLS_DIR)/library
LDLIBS += -lmbedtls -lmbedx509 -lmbedcrypto
CPPFLAGSG += -I$(PWD) -DMBEDTLS_CONFIG_FILE="<mbedtls_nucleo_config.h>"

include ../test.mk

%_der.c: %.der
	xxd -i $< |sed 's/\<unsigned\>/const unsigned/g' >$@

clean: libmbedtls_clean

libmbedtls_clean:
	cd $(MBEDTLS_DIR); \
		make -s clean;

mbedtls_test.o: $(MBEDTLS_DIR)/library/libmbedtls.a

$(MBEDTLS_DIR)/library/libmbedtls.a:
	cd $(MBEDTLS_DIR); \
		export CPPFLAGS="-I/home/marcel/workspace/nucleo_tests/include -D_POSIX_SOURCE=200809L -D_POSIX_C_SOURCE=200809L -D_POSIX_TIMERS=200809L -D_POSIX_MONOTONIC_CLOCK=200809L -D_POSIX_CLOCK_SELECTION=200809L -D_XOPEN_SOURCE=700 -I$(PWD) -DMBEDTLS_CONFIG_FILE=\"<mbedtls_nucleo_config.h>\""; \
		export CFLAGS="$(ARCH_FLAGS) -g -Os -ffunction-sections $$CPPFLAGS"; \
		export LDFLAGS="$(ARCH_FLAGS) -g --specs=nosys.specs -L/home/marcel/workspace/nucleo_tests/src/ -L/home/marcel/workspace/nucleo_tests/libopencm3/lib"; \
		export CC=arm-none-eabi-gcc; \
		export AR=arm-none-eabi-ar; \
		export LIBS="-lposix -lopencm3_stm32f1"; \
		make lib

After changing the path in the makefile it works without a problem, but I have one question I have a DEV Board with a STM32F407 µC do I need to change something?
Could you fix this bug in the Makefile?
Thank you for your work

**Comment by balau** [comment]
Thank you! I changed the Makefile to remove user-dependent directories, sorry it slipped.
To build for STM32F407 you would probably just need to create a new `scripts/stm32f407xx.ld` memory map file, a `scripts/libopencm3.stm32f407xx.mk` sub-makefile and include it in `tests/test.mk` instead of the one that is currently used.
